license="MIT"
modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Noobanidus/DynamicTreesVoyage/issues"

[[mods]]
modId="dtvoyage"
version="${version}"
displayName="Dynamic Trees for Voyage"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-voyage"
logoFile="dtt-logo.png"
credits=""
authors="Noobanidus"
description='''
Adds Dynamic Trees compatibility to Voyage.
'''

[[dependencies.dtvoyage]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvoyage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtvoyage]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0-Beta13,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtvoyage]]
    modId="voyage"
    mandatory=true
    versionRange="[1.0.3,)"
    ordering="AFTER"
    side="BOTH"
